export const securityGroupsStyles = {
  container: {
    padding: "2rem",
    maxWidth: "1400px",
    margin: "0 auto",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "2rem",
  },
  headerTitleGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "0.25rem",
  },
  userIp: {
    fontSize: "0.875rem",
    color: "text.secondary",
  },
  title: {
    fontSize: "2.25rem",
    fontWeight: "bold",
    color: "primary.400",
  },
  filters: {
    display: "flex",
    gap: "1rem",
    marginBottom: "2rem",
    padding: "1rem",
    backgroundColor: "surface",
    borderRadius: "0.5rem",
    flexWrap: "wrap",
    border: "1px solid",
    borderColor: "border",
  },
  filterGroup: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  label: {
    fontWeight: "500",
    color: "text.secondary",
  },
  input: {
    padding: "0.5rem",
    borderRadius: "0.375rem",
    border: "1px solid",
    borderColor: "border",
    backgroundColor: "background",
    color: "text.primary",
    minWidth: "220px",
  },
  select: {
    padding: "0.5rem",
    borderRadius: "0.375rem",
    border: "1px solid",
    borderColor: "border",
    backgroundColor: "surface",
    color: "text.primary",
    minWidth: "180px",
    appearance: "none",
    WebkitAppearance: "none",
    MozAppearance: "none",
    transition: "border-color 0.2s ease, box-shadow 0.2s ease",
    _focus: {
      borderColor: "primary.400",
      boxShadow: "0 0 0 2px rgba(59,130,246,0.35)",
      outline: "none",
    },
  },
  checkboxLabel: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    cursor: "pointer",
  },
  checkbox: {
    width: "1rem",
    height: "1rem",
    cursor: "pointer",
  },
  tableContainer: {
    overflowX: "auto",
    borderRadius: "0.75rem",
    border: "1px solid",
    borderColor: "border",
    backgroundColor: "surface",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    minWidth: "960px",
  },
  tableHeaderRow: {
    backgroundColor: "rgba(59, 130, 246, 0.1)",
  },
  tableHeaderCell: {
    textAlign: "left",
    fontSize: "0.875rem",
    fontWeight: "600",
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "text.secondary",
    padding: "0.75rem 1rem",
    borderBottom: "1px solid",
    borderColor: "border",
  },
  tableHeaderSortButton: {
    display: "flex",
    alignItems: "center",
    gap: "0.4rem",
    background: "transparent",
    border: "none",
    color: "inherit",
    font: "inherit",
    cursor: "pointer",
    padding: 0,
    textTransform: "inherit",
    _hover: {
      color: "text.primary",
    },
  },
  tableHeaderSortIcon: {
    fontSize: "0.75rem",
    opacity: 0.7,
  },
  tableBodyRow: {
    transition: "background-color 0.2s",
    borderBottom: "1px solid",
    borderColor: "rgba(255, 255, 255, 0.05)",
  },
  tableBodyRowClickable: {
    cursor: "pointer",
    "&:hover": {
      backgroundColor: "rgba(59, 130, 246, 0.08)",
    },
  },
  tableCell: {
    padding: "1rem",
    verticalAlign: "top",
    fontSize: "0.95rem",
    color: "text.primary",
  },
  tableNameCell: {
    display: "flex",
    flexDirection: "column",
    gap: "0.35rem",
  },
  tableNameTitle: {
    fontSize: "1rem",
    fontWeight: "600",
    color: "primary.300",
  },
  tableNameMeta: {
    display: "flex",
    gap: "0.5rem",
    flexWrap: "wrap",
    fontSize: "0.8rem",
    color: "text.secondary",
  },
  tableDescription: {
    color: "text.secondary",
    lineHeight: "1.5",
  },
  tableCounts: {
    display: "flex",
    flexDirection: "column",
    gap: "0.25rem",
    fontFamily: "monospace",
  },
  warningList: {
    display: "flex",
    gap: "0.5rem",
    flexWrap: "wrap",
  },
  warningChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.25rem",
    padding: "0.25rem 0.5rem",
    borderRadius: "999px",
    fontSize: "0.75rem",
    fontWeight: "600",
  },
  warningChipCritical: {
    backgroundColor: "error",
    color: "white",
  },
  warningChipWarning: {
    backgroundColor: "warning",
    color: "black",
  },
  loadingContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "400px",
    gap: "1rem",
  },
  spinner: {
    width: "3rem",
    height: "3rem",
    border: "3px solid",
    borderColor: "primary.200",
    borderTopColor: "primary.500",
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
  },
  errorContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "400px",
    gap: "1rem",
    color: "error",
  },
  noResults: {
    textAlign: "center",
    color: "text.secondary",
    padding: "2.5rem",
    fontSize: "0.95rem",
  },
} as const;
