export const securityGroupsStyles = {
  container: {
    padding: "2rem",
    maxWidth: "1400px",
    margin: "0 auto",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "2rem",
  },
  title: {
    fontSize: "2rem",
    fontWeight: "bold",
    color: "primary.400",
  },
  filters: {
    display: "flex",
    gap: "1rem",
    marginBottom: "2rem",
    padding: "1rem",
    backgroundColor: "surface",
    borderRadius: "0.5rem",
    flexWrap: "wrap",
  },
  filterGroup: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  label: {
    fontWeight: "500",
    color: "text.secondary",
  },
  input: {
    padding: "0.5rem",
    borderRadius: "0.375rem",
    border: "1px solid",
    borderColor: "border",
    backgroundColor: "background",
    color: "text.primary",
    minWidth: "200px",
  },
  select: {
    padding: "0.5rem",
    borderRadius: "0.375rem",
    border: "1px solid",
    borderColor: "border",
    backgroundColor: "background",
    color: "text.primary",
    minWidth: "150px",
  },
  checkboxLabel: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    cursor: "pointer",
  },
  checkbox: {
    width: "1rem",
    height: "1rem",
    cursor: "pointer",
  },
  cardsContainer: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(500px, 1fr))",
    gap: "1.5rem",
  },
  loadingContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "400px",
    gap: "1rem",
  },
  spinner: {
    width: "3rem",
    height: "3rem",
    border: "3px solid",
    borderColor: "primary.200",
    borderTopColor: "primary.500",
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
  },
  errorContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "400px",
    gap: "1rem",
    color: "error",
  },
  noResults: {
    textAlign: "center",
    color: "text.secondary",
    padding: "2rem",
  },
} as const;
