export const securityGroupDetailStyles = {
  container: {
    padding: "2rem",
    maxWidth: "1200px",
    margin: "0 auto",
    display: "flex",
    flexDirection: "column",
    gap: "2rem",
  },
  header: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
  },
  backLink: {
    width: "fit-content",
  },
  title: {
    fontSize: "2.25rem",
    fontWeight: "700",
    color: "primary.300",
  },
  subtitle: {
    fontSize: "1rem",
    color: "text.secondary",
    fontFamily: "monospace",
  },
  metaList: {
    display: "flex",
    gap: "0.75rem",
    flexWrap: "wrap",
    fontSize: "0.95rem",
    color: "text.secondary",
  },
  metaItem: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.35rem",
    padding: "0.35rem 0.6rem",
    backgroundColor: "rgba(59, 130, 246, 0.08)",
    borderRadius: "999px",
    fontFamily: "monospace",
  },
  description: {
    color: "text.primary",
    lineHeight: "1.7",
    fontSize: "1rem",
  },
  infoGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: "1rem",
  },
  infoCard: {
    padding: "1rem",
    backgroundColor: "surface",
    borderRadius: "0.75rem",
    border: "1px solid",
    borderColor: "border",
    display: "flex",
    flexDirection: "column",
    gap: "0.35rem",
  },
  infoLabel: {
    fontSize: "0.85rem",
    color: "text.secondary",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  infoValue: {
    fontSize: "1.35rem",
    fontWeight: "600",
    color: "primary.300",
  },
  section: {
    display: "flex",
    flexDirection: "column",
    gap: "1.5rem",
  },
  sectionHeader: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  },
  sectionTitle: {
    fontSize: "1.5rem",
    fontWeight: "600",
    color: "text.primary",
  },
  sectionSubtitle: {
    fontSize: "0.95rem",
    color: "text.secondary",
  },
  tagList: {
    display: "flex",
    gap: "0.5rem",
    flexWrap: "wrap",
  },
  tagChip: {
    padding: "0.3rem 0.6rem",
    backgroundColor: "rgba(147, 197, 253, 0.15)",
    borderRadius: "0.5rem",
    fontSize: "0.8rem",
    color: "primary.200",
    fontFamily: "monospace",
  },
  formContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    padding: "1rem",
    borderRadius: "0.75rem",
    border: "1px solid",
    borderColor: "border",
    backgroundColor: "surface",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: "1rem",
  },
  formField: {
    display: "flex",
    flexDirection: "column",
    gap: "0.35rem",
  },
  formFieldFull: {
    gridColumn: "1 / -1",
  },
  formLabel: {
    fontSize: "0.85rem",
    fontWeight: "600",
    color: "text.secondary",
  },
  formInput: {
    padding: "0.5rem",
    border: "1px solid",
    borderColor: "border",
    borderRadius: "0.375rem",
    backgroundColor: "surface",
    color: "text.primary",
    fontSize: "0.95rem",
    transition: "border-color 0.2s ease, box-shadow 0.2s ease",
    _focus: {
      borderColor: "primary.400",
      boxShadow: "0 0 0 2px rgba(59,130,246,0.35)",
      outline: "none",
    },
  },
  formSelect: {
    padding: "0.5rem",
    border: "1px solid",
    borderColor: "border",
    borderRadius: "0.375rem",
    backgroundColor: "surface",
    color: "text.primary",
    fontSize: "0.95rem",
    appearance: "none",
    WebkitAppearance: "none",
    MozAppearance: "none",
    transition: "border-color 0.2s ease, box-shadow 0.2s ease",
    _focus: {
      borderColor: "primary.400",
      boxShadow: "0 0 0 2px rgba(59,130,246,0.35)",
      outline: "none",
    },
  },
  formActions: {
    display: "flex",
    gap: "0.75rem",
    alignItems: "center",
  },
  formHelper: {
    fontSize: "0.75rem",
    color: "text.secondary",
  },
  formHelperRow: {
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
    flexWrap: "wrap",
  },
  formCheckboxLabel: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.5rem",
    fontSize: "0.85rem",
    color: "text.secondary",
  },
  formHelperButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "1.5rem",
    height: "1.5rem",
    borderRadius: "999px",
    border: "1px solid",
    borderColor: "border",
    backgroundColor: "transparent",
    color: "text.secondary",
    fontSize: "0.85rem",
    cursor: "pointer",
  },
  formMessage: {
    fontSize: "0.85rem",
  },
  formMessageError: {
    color: "error",
  },
  formMessageSuccess: {
    color: "success",
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 9999,
    backdropFilter: "blur(2px)",
    padding: "1rem",
  },
  modalContent: {
    backgroundColor: "surface",
    padding: "1.5rem",
    borderRadius: "0.75rem",
    border: "1px solid",
    borderColor: "border",
    width: "480px",
    maxWidth: "100%",
    boxShadow: "xl",
    display: "flex",
    flexDirection: "column",
    gap: "1.5rem",
  },
  modalTitle: {
    fontSize: "1.25rem",
    fontWeight: "600",
    color: "text.primary",
  },
  modalDescription: {
    fontSize: "0.95rem",
    color: "text.secondary",
    lineHeight: "1.6",
  },
  modalActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "0.75rem",
  },
  tableCheckbox: {
    width: "1rem",
    height: "1rem",
    cursor: "pointer",
  },
} as const;
